language: node_js

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.8

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

defaults: &defaults
  script:
    # print all Travis environment variables for debugging
    - $(npm bin)/print-env TRAVIS
    - npm start -- --silent &
    - npm run cy:run
    # after all tests finish running we need
    # to kill all background jobs (like "npm start &")
    - kill $(jobs -p) || true
notifications:
  slack:
    secure: XdmOobsi4wzrlcJWjWis3zfdk04/y3sdgYk0U2O2P5owGFW4cJk3ZX0yFaTgxuM+hiWiN425Zd8RLGDNl9VaX5Gf4tWRGoNtNHUemUTg2FtT2wFH6Z+EBGLrjqcdy39rKrEIU7S5Z2xaUnrrgR0a7j7sJGe25dG9j4vhmbAl0wKBzxnZQUmD0/Zvd09tHOjh3fHnsVvkhGQvH9BcISDWU0jwYdvZV03FPVDY2fgF25rbinuYA3nkL21lodevJNCVrBF8WKWzRgLty0yuX/aSAMIAKM+XtZykPbMql2xLFO7B8lVjWmg0JoO7TayXaG5WQkaz3BlLg2olZFkpL4ar3hi2xAE84ChR0VYXt2weSLFl94jd6M/UeSINJoR8AaaS845T6xwfpSddzCTtZ6+Ts72wLfVN27J0yiDYViRHL9EP7EZOYdYYVvx0mNl24XWop2MmpWX0fWiJWpmPbhHH3Y7UomzMpQVjD+raoZIE0R6wwa5oVX2krooT0bEzo8VmdCrzgDO8YXFOy7krG0LFfoeJQwE5cYbodWebTydNzGL6z/qtCM1dFXl87Q9I61vhLa0XbttyLEALNimjEcrMW6boxLbuwxpuCX6RWHNP8JrZxNbxrFHjY9Oq1NRIb+z5oJ0ljLaBsaUymToEHXYrmB6RRVi15dBoklnSFo1ldq4=
  on_success: change
  on_failure: always
